// Wire contract between a scannerl Coordinator and its Workers
// (Milestone 2: distributed mode). See internal/coordinator and
// internal/worker for the Go implementations either side of this.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.3
// source: scanner.proto

package scannerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Outcome mirrors internal/fpmodule.Outcome. OUTCOME_UNSPECIFIED is
// proto3's mandatory zero value; it is never produced by a well-formed
// conversion, so its presence on the wire signals a missing/corrupt
// field rather than aliasing OUTCOME_OK.
type Outcome int32

const (
	Outcome_OUTCOME_UNSPECIFIED   Outcome = 0
	Outcome_OUTCOME_OK            Outcome = 1
	Outcome_OUTCOME_ERROR_UP      Outcome = 2
	Outcome_OUTCOME_ERROR_UNKNOWN Outcome = 3
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_OK",
		2: "OUTCOME_ERROR_UP",
		3: "OUTCOME_ERROR_UNKNOWN",
	}
	Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED":   0,
		"OUTCOME_OK":            1,
		"OUTCOME_ERROR_UP":      2,
		"OUTCOME_ERROR_UNKNOWN": 3,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_scanner_proto_enumTypes[0].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_scanner_proto_enumTypes[0]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{0}
}

// Target mirrors internal/target.Target field-for-field.
type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	IsDomain      bool                   `protobuf:"varint,3,opt,name=is_domain,json=isDomain,proto3" json:"is_domain,omitempty"`
	Arg           []string               `protobuf:"bytes,4,rep,name=arg,proto3" json:"arg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{0}
}

func (x *Target) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Target) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Target) GetIsDomain() bool {
	if x != nil {
		return x.IsDomain
	}
	return false
}

func (x *Target) GetArg() []string {
	if x != nil {
		return x.Arg
	}
	return nil
}

// Result mirrors internal/output.Record, with its embedded
// fpmodule.Result flattened in (matching internal/output/outputs
// jsonlines.go's jsonRecord shape). Result.Value (documented as one of:
// string, bool, []string, []any, or fmt.Stringer/netip.Addr) is
// JSON-encoded into value_json rather than modeled as a oneof/Any, so the
// wire schema doesn't need to change as module Value shapes evolve. An
// empty value_json means a nil Value.
type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Outcome       Outcome                `protobuf:"varint,4,opt,name=outcome,proto3,enum=scannerl.Outcome" json:"outcome,omitempty"`
	ValueJson     string                 `protobuf:"bytes,5,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Result) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Result) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Result) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *Result) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

// WorkerHello identifies a worker connecting for its target shard. It is
// not used to decide shard assignment (arrival order does that); it's
// carried only for the coordinator's own logging/diagnostics.
type WorkerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHello) Reset() {
	*x = WorkerHello{}
	mi := &file_scanner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHello) ProtoMessage() {}

func (x *WorkerHello) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHello.ProtoReflect.Descriptor instead.
func (*WorkerHello) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerHello) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// ReportAck is ReportResults' single response, sent once after the
// worker's result stream closes.
type ReportAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      int64                  `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAck) Reset() {
	*x = ReportAck{}
	mi := &file_scanner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAck) ProtoMessage() {}

func (x *ReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAck.ProtoReflect.Descriptor instead.
func (*ReportAck) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{3}
}

func (x *ReportAck) GetReceived() int64 {
	if x != nil {
		return x.Received
	}
	return 0
}

var File_scanner_proto protoreflect.FileDescriptor

const file_scanner_proto_rawDesc = "" +
	"\n" +
	"\rscanner.proto\x12\bscannerl\"_\n" +
	"\x06Target\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1b\n" +
	"\tis_domain\x18\x03 \x01(\bR\bisDomain\x12\x10\n" +
	"\x03arg\x18\x04 \x03(\tR\x03arg\"\x98\x01\n" +
	"\x06Result\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12+\n" +
	"\aoutcome\x18\x04 \x01(\x0e2\x11.scannerl.OutcomeR\aoutcome\x12\x1d\n" +
	"\n" +
	"value_json\x18\x05 \x01(\tR\tvalueJson\"*\n" +
	"\vWorkerHello\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"'\n" +
	"\tReportAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\x03R\breceived*c\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"OUTCOME_OK\x10\x01\x12\x14\n" +
	"\x10OUTCOME_ERROR_UP\x10\x02\x12\x19\n" +
	"\x15OUTCOME_ERROR_UNKNOWN\x10\x032|\n" +
	"\aScanner\x127\n" +
	"\n" +
	"GetTargets\x12\x15.scannerl.WorkerHello\x1a\x10.scannerl.Target0\x01\x128\n" +
	"\rReportResults\x12\x10.scannerl.Result\x1a\x13.scannerl.ReportAck(\x01B9Z7github.com/xieyanran/scannerl-go/internal/rpc/scannerpbb\x06proto3"

var (
	file_scanner_proto_rawDescOnce sync.Once
	file_scanner_proto_rawDescData []byte
)

func file_scanner_proto_rawDescGZIP() []byte {
	file_scanner_proto_rawDescOnce.Do(func() {
		file_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scanner_proto_rawDesc), len(file_scanner_proto_rawDesc)))
	})
	return file_scanner_proto_rawDescData
}

var file_scanner_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_scanner_proto_goTypes = []any{
	(Outcome)(0),        // 0: scannerl.Outcome
	(*Target)(nil),      // 1: scannerl.Target
	(*Result)(nil),      // 2: scannerl.Result
	(*WorkerHello)(nil), // 3: scannerl.WorkerHello
	(*ReportAck)(nil),   // 4: scannerl.ReportAck
}
var file_scanner_proto_depIdxs = []int32{
	0, // 0: scannerl.Result.outcome:type_name -> scannerl.Outcome
	3, // 1: scannerl.Scanner.GetTargets:input_type -> scannerl.WorkerHello
	2, // 2: scannerl.Scanner.ReportResults:input_type -> scannerl.Result
	1, // 3: scannerl.Scanner.GetTargets:output_type -> scannerl.Target
	4, // 4: scannerl.Scanner.ReportResults:output_type -> scannerl.ReportAck
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scanner_proto_init() }
func file_scanner_proto_init() {
	if File_scanner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scanner_proto_rawDesc), len(file_scanner_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scanner_proto_goTypes,
		DependencyIndexes: file_scanner_proto_depIdxs,
		EnumInfos:         file_scanner_proto_enumTypes,
		MessageInfos:      file_scanner_proto_msgTypes,
	}.Build()
	File_scanner_proto = out.File
	file_scanner_proto_goTypes = nil
	file_scanner_proto_depIdxs = nil
}
