// Wire contract between a scannerl Coordinator and its Workers
// (Milestone 2: distributed mode). See internal/coordinator and
// internal/worker for the Go implementations either side of this.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: scanner.proto

package scannerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Scanner_GetTargets_FullMethodName    = "/scannerl.Scanner/GetTargets"
	Scanner_ReportResults_FullMethodName = "/scannerl.Scanner/ReportResults"
)

// ScannerClient is the client API for Scanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScannerClient interface {
	// GetTargets is called once per worker on connect. The coordinator
	// blocks the response until exactly -workers WorkerHello calls have
	// arrived, computes even shares, streams this worker's shard down as
	// individual Target messages, then closes the stream. No dynamic
	// rebalancing happens after that: it is a one-time, static push.
	GetTargets(ctx context.Context, in *WorkerHello, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Target], error)
	// ReportResults: the worker streams one Result per finished probe as
	// it's produced. The coordinator reads until the worker closes the
	// stream (feeding every Result into its own output.Sink along the
	// way), then returns one ReportAck.
	ReportResults(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Result, ReportAck], error)
}

type scannerClient struct {
	cc grpc.ClientConnInterface
}

func NewScannerClient(cc grpc.ClientConnInterface) ScannerClient {
	return &scannerClient{cc}
}

func (c *scannerClient) GetTargets(ctx context.Context, in *WorkerHello, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Target], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Scanner_ServiceDesc.Streams[0], Scanner_GetTargets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerHello, Target]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scanner_GetTargetsClient = grpc.ServerStreamingClient[Target]

func (c *scannerClient) ReportResults(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Result, ReportAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Scanner_ServiceDesc.Streams[1], Scanner_ReportResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Result, ReportAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scanner_ReportResultsClient = grpc.ClientStreamingClient[Result, ReportAck]

// ScannerServer is the server API for Scanner service.
// All implementations must embed UnimplementedScannerServer
// for forward compatibility.
type ScannerServer interface {
	// GetTargets is called once per worker on connect. The coordinator
	// blocks the response until exactly -workers WorkerHello calls have
	// arrived, computes even shares, streams this worker's shard down as
	// individual Target messages, then closes the stream. No dynamic
	// rebalancing happens after that: it is a one-time, static push.
	GetTargets(*WorkerHello, grpc.ServerStreamingServer[Target]) error
	// ReportResults: the worker streams one Result per finished probe as
	// it's produced. The coordinator reads until the worker closes the
	// stream (feeding every Result into its own output.Sink along the
	// way), then returns one ReportAck.
	ReportResults(grpc.ClientStreamingServer[Result, ReportAck]) error
	mustEmbedUnimplementedScannerServer()
}

// UnimplementedScannerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScannerServer struct{}

func (UnimplementedScannerServer) GetTargets(*WorkerHello, grpc.ServerStreamingServer[Target]) error {
	return status.Error(codes.Unimplemented, "method GetTargets not implemented")
}
func (UnimplementedScannerServer) ReportResults(grpc.ClientStreamingServer[Result, ReportAck]) error {
	return status.Error(codes.Unimplemented, "method ReportResults not implemented")
}
func (UnimplementedScannerServer) mustEmbedUnimplementedScannerServer() {}
func (UnimplementedScannerServer) testEmbeddedByValue()                 {}

// UnsafeScannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScannerServer will
// result in compilation errors.
type UnsafeScannerServer interface {
	mustEmbedUnimplementedScannerServer()
}

func RegisterScannerServer(s grpc.ServiceRegistrar, srv ScannerServer) {
	// If the following call panics, it indicates UnimplementedScannerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Scanner_ServiceDesc, srv)
}

func _Scanner_GetTargets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WorkerHello)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScannerServer).GetTargets(m, &grpc.GenericServerStream[WorkerHello, Target]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scanner_GetTargetsServer = grpc.ServerStreamingServer[Target]

func _Scanner_ReportResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ScannerServer).ReportResults(&grpc.GenericServerStream[Result, ReportAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scanner_ReportResultsServer = grpc.ClientStreamingServer[Result, ReportAck]

// Scanner_ServiceDesc is the grpc.ServiceDesc for Scanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scannerl.Scanner",
	HandlerType: (*ScannerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTargets",
			Handler:       _Scanner_GetTargets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReportResults",
			Handler:       _Scanner_ReportResults_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "scanner.proto",
}
